change directory

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -33,8 +33,8 @@ jobs:
           username: ubuntu
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            echo "📂 Changing directory to /app/backend..."
-            cd /app/backend || { echo "❌ /app/backend not found"; exit 1; }
+            echo "📂 Changing directory to /app..."
+            cd /app || { echo "❌ /app not found"; exit 1; }
 
             echo "🔄 Pulling latest code..."
             git pull origin main || { echo "❌ Git pull failed"; exit 1; }
